# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f091467640afccf2f5920b41d55f5d387d0cbb061f2a826da3779d1e05d0668ec5f219523ed4e107fbd358513d945f5576fd75d97b157eea1f54e1e3e1770163

test:
  secret_key_base: b075fff3ecf7fba09e78872cbcacd3f8ee413ff9d030ea131331f33dde7e9492abb4a7757d4f8e438665726654ec4ff4fde79f5193a87bda50c30d25fee92cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
